[package]
name = "actix_api"
version = "0.1.0"
authors = ["Lekhman-vold <volodya.l@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
futures = "0.1"
serde = "1.0.125"
